version: "3.9"  # optional since v1.27.0

services:
  api:
    container_name: "app-back"
    build:
      context: ./Back-End/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./Back-End:/usr/src/app
      # - /usr/src/app/node_modules
    # command: npm run start:dev
    env_file:
        - Back-End/.env
    ports:
      - 5555:5555
      - 3000:3000
    networks:
      - transcendence

  postgres:
    image: postgres:latest
    container_name: "postgres"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - Back-End/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - transcendence

networks:
  transcendence:

volumes:
  postgres:


