version: "3.9"  # optional since v1.27.0

services:
  api:
    container_name: "app-back"
    build:
      context: ./Back-End/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./Back-End:/usr/src/app
      - back_node_modules:/usr/src/app/node_modules
    # command: npm run start:dev
    env_file:
        - ./Back-End/.env
    ports:
      - 5555:5555
      - 3000:3000
      - 8001:8001
    networks:
      - transcendence

  postgres:
    image: postgres:latest
    container_name: "postgres"
    restart: always
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./Back-End/.env
    networks:
      - transcendence


  frontend:
    container_name: react
    build:
      context: ./Front-End/
      dockerfile: Dockerfile
    volumes:
      - ./Front-End:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules
    # command: npm run dev
    ports:
      - 8080:8080
    networks:
      - transcendence

networks:
  transcendence:

volumes:
  my-postgres-data:
  front_node_modules:
  back_node_modules:


